### PR TITLE
Custom Error Page

### PR DESCRIPTION
**Pull request by saadazghour**
i hope this contribution it make effect :sunglasses:

### CODE REVIEW

**Comment by saadazghour** [comment]
@xHacker404 , Add file .gitignore to resolve Merge conflict , __pycache__, db.sqlite3,  ect..

**Review by dimiksonkha — APPROVED** [review]

**Comment by dimiksonkha** [comment]
@SAzghour Thanks for you contribution.Could you please test the site and create issues?

**Comment by dimiksonkha** [comment]
Hi SAzghour,
Thanks for your contribution to my repository. Your contribution improved
my blog engine significantly . Yesterday I got problem with merging your
pull request. Not it is fixed.
For admin access please use: xHacker121 as username and 12345 as password
I've custom admin panel which you can login through the above mentioned
username and password.

Regards
Sulaiman Haque

**Comment by saadazghour** [comment]
Sure, :+1:

**Pull request closed without merging**
